# Generated by Django 4.2 on 2024-04-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_status_alter_card_adds_alter_card_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, db_column='Tags', related_name='cards', to='cards.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='cardtag',
            name='card',
            field=models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Карточка'),
        ),
        migrations.AlterField(
            model_name='cardtag',
            name='tag',
            field=models.ForeignKey(db_column='TagID', on_delete=django.db.models.deletion.CASCADE, to='cards.tag', verbose_name='Тег'),
        ),
    ]
