# Generated by Django 4.2 on 2024-06-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritesWords',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_learned', models.BooleanField(choices=[(False, 'Не выучено'), (True, 'Выучено')], default=False, verbose_name='Выучено')),
                ('errors_word', models.IntegerField(db_column='Errors_word', default=0, verbose_name='Количество ошибок')),
                ('rights_word', models.IntegerField(db_column='Rights_word', default=0, verbose_name='Количество ответов')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное слово',
                'verbose_name_plural': 'Избранные слова',
                'db_table': 'FavouritesWords',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_column='En_word', max_length=100, verbose_name='Слово')),
                ('transcription', models.CharField(db_column='Transcription', max_length=100, null=True, verbose_name='Транскрипция')),
                ('rus_word', models.CharField(db_column='Rus_word', max_length=100, verbose_name='Перевод')),
                ('favourites_word', models.ManyToManyField(related_name='words', through='flip_cards_app.FavouritesWords', to=settings.AUTH_USER_MODEL, verbose_name='Избранные')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'db_table': 'allwords',
            },
        ),
        migrations.AddField(
            model_name='favouriteswords',
            name='word',
            field=models.ForeignKey(db_column='WordID', on_delete=django.db.models.deletion.CASCADE, to='flip_cards_app.word'),
        ),
        migrations.AlterUniqueTogether(
            name='favouriteswords',
            unique_together={('word', 'user')},
        ),
    ]
