# Generated by Django 4.2 on 2024-06-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flip_cards_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='status',
            field=models.BooleanField(choices=[(False, 'Не проверено'), (True, 'Проверено')], default=False, verbose_name='Проверено'),
        ),
    ]
