# Generated by Django 5.0.6 on 2024-07-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flip_cards_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteswords',
            name='user',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='word',
            name='favorites_word',
            field=models.ManyToManyField(related_name='favorites_word', through='flip_cards_app.FavoritesWords', to=settings.AUTH_USER_MODEL, verbose_name='Избранные'),
        ),
        migrations.AddField(
            model_name='favoriteswords',
            name='word',
            field=models.ForeignKey(db_column='WordID', on_delete=django.db.models.deletion.CASCADE, to='flip_cards_app.word'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteswords',
            unique_together={('word', 'user')},
        ),
    ]
