# Generated by Django 5.1.2 on 2025-03-03 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flip_cards_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteFolder",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="id", primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        db_column="Name", max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка избранного",
                "verbose_name_plural": "Папки избранного",
                "db_table": "FavoriteFolders",
            },
        ),
        migrations.AddField(
            model_name="favoriteswords",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flip_cards_app.favoritefolder",
            ),
        ),
    ]
