# Generated by Django 5.1.2 on 2025-03-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flip_cards_app", "0003_favoritefolder_favoriteswords_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoriteswords",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flip_cards_app.favoritefolder",
            ),
        ),
    ]
