# Generated by Django 4.2 on 2024-05-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_column='En_word', max_length=100, verbose_name='Слово')),
                ('transcription', models.CharField(db_column='Transcription', max_length=100, verbose_name='Транскрипция')),
                ('rus_word', models.CharField(db_column='Rus_word', max_length=100, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'db_table': 'allwords',
            },
        ),
    ]
