# Generated by Django 5.0.6 on 2024-05-23 18:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_column='En_word', max_length=100, verbose_name='Слово')),
                ('transcription', models.CharField(db_column='Transcription', max_length=100, null=True, verbose_name='Транскрипция')),
                ('rus_word', models.CharField(db_column='Rus_word', max_length=100, verbose_name='Перевод')),
                ('favourites_word', models.ManyToManyField(blank=True, related_name='favourites_word', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'db_table': 'allwords',
            },
        ),
    ]
