# Generated by Django 5.0.6 on 2024-06-04 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False, verbose_name='ID')),
                ('en_word', models.CharField(db_column='En_word', max_length=100, verbose_name='Слово')),
                ('transcription', models.CharField(db_column='Transcription', max_length=100, null=True, verbose_name='Транскрипция')),
                ('rus_word', models.CharField(db_column='Rus_word', max_length=100, verbose_name='Перевод')),
            ],
            options={
                'verbose_name': 'Словарь',
                'verbose_name_plural': 'Словари',
                'db_table': 'allwords',
            },
        ),
        migrations.CreateModel(
            name='FavouritesWords',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('is_learned', models.BooleanField(choices=[(False, 'Не выучено'), (True, 'Выучено')], default=False, verbose_name='Выучено')),
                ('card', models.ForeignKey(db_column='CardID', on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное слово',
                'verbose_name_plural': 'Избранные слова',
                'db_table': 'FavouritesWords',
                'unique_together': {('card', 'user')},
            },
        ),
        migrations.AddField(
            model_name='card',
            name='favourites_word',
            field=models.ManyToManyField(related_name='cards', through='cards.FavouritesWords', to=settings.AUTH_USER_MODEL, verbose_name='Избранные'),
        ),
    ]
