# Generated by Django 4.2 on 2024-05-16 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='favorites_words',
            field=models.ManyToManyField(blank=True, related_name='favorite_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
