# Generated by Django 4.2 on 2024-05-17 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_card_favorites_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='favorites_words',
            field=models.ManyToManyField(blank=True, related_name='favorites_words', to=settings.AUTH_USER_MODEL),
        ),
    ]
