# Generated by Django 4.2 on 2024-05-17 07:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_alter_card_favorites_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='favorites_words',
        ),
        migrations.AddField(
            model_name='card',
            name='favourites_word',
            field=models.ManyToManyField(blank=True, related_name='favourites_word', to=settings.AUTH_USER_MODEL),
        ),
    ]
