# Generated by Django 5.0.6 on 2024-06-11 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_favouriteswords_errors_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteswords',
            name='rights_word',
            field=models.IntegerField(db_column='Rights_word', default=0, verbose_name='Количество ответов'),
        ),
    ]
